title: BookEnjenn
description: >- # this means to ignore newlines until "baseurl:"
  I Love Books | Book Reviews and More! | Book Enjenn | bookenjenn.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bookenjenn.com" # the base hostname & protocol for your site, e.g. http://example.com

date_format: "%B %-d, %Y"
excerpt_separator: "<!--excs-->"

dentoniteUrl: http://www.thedentonite.com/culture?author=5c3cbfe5352f53368c1260fe
linkedinUrl: https://www.linkedin.com/in/jennifer-chastka-915570145
goodreadsUrl: https://www.goodreads.com/user/show/16060897-jenn-chastka

privacyUpdate: '2022-10-5'

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
